name: CI

on:
  push:
  pull_request:

jobs:
  node-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for package.json
        id: pkg
        run: |
          if [ -f package.json ]; then
            echo "has_pkg=true" >> $GITHUB_OUTPUT
          else
            echo "has_pkg=false" >> $GITHUB_OUTPUT
          fi

      - name: Setup Node
        if: steps.pkg.outputs.has_pkg == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        if: steps.pkg.outputs.has_pkg == 'true'
        run: npm install

      - name: Lint
        if: steps.pkg.outputs.has_pkg == 'true'
        run: npm run lint --if-present

      - name: Tests
        if: steps.pkg.outputs.has_pkg == 'true'
        run: npm test --if-present

      - name: Build
        if: steps.pkg.outputs.has_pkg == 'true'
        run: npm run build --if-present

      - name: No project yet
        if: steps.pkg.outputs.has_pkg == 'false'
        run: echo "package.json не найден — проект ещё не инициализирован. CI пропущен."
